name: ci-security-scanner-checks

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  trivy_scan:
    name: trivy-scans
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v7
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4.36.3
        with:
          sarif_file: 'trivy-results.sarif'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  nancy_check:
    name: nancy-check
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
        
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Get Go Version
        run: |
          #!/bin/bash
          GOVERSION=$({ [ -f .go-version ] && cat .go-version; })
          echo "GOVERSION=$GOVERSION" >> $GITHUB_ENV
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GOVERSION }}
      - name: WriteGoList
        run: go list -json -m all > go.list
      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@395e2fb168f674f96502e5652103d112899ea369 # main
        with:
          nancyVersion: "v1.0.48"
          nancyCommand: sleuth --loud  
  ossf_scan:
    name: openssf-scorecard
    runs-on: ubuntu-20.04
    permissions:
      security-events: write
      id-token: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
        
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Run analysis
        uses: ossf/scorecard-action@50757822a4ac41af1c2f5572df4e1c1a5ae50c03 # main
        with:
          results_file: 'ossf-results.sarif'
          results_format: sarif
          publish_results: true
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # main
        with:
          name: 'OSSF Sarif file'
          path: 'ossf-results.sarif'
          retention-days: 5
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4.36.3
        with:
          sarif_file: 'ossf-results.sarif'